# Generated by Django 5.2.17 on 2026-08-22 06:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('months', models.PositiveSmallIntegerField(unique=True)),
                ('discount_bps', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10000)])),
                ('onboarding_bps', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(10000)])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('months',),
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('order', models.PositiveSmallIntegerField(unique=True)),
                ('base_monthly_toman', models.PositiveBigIntegerField()),
                ('included_users', models.PositiveIntegerField()),
                ('included_endpoints', models.PositiveIntegerField()),
                ('included_servers', models.PositiveIntegerField(default=0)),
                ('included_sites', models.PositiveIntegerField(default=1)),
                ('currency', models.CharField(default='IRT', editable=False, max_length=3)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='PackageFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('order', 'key'),
            },
        ),
        migrations.CreateModel(
            name='AddonRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('addon_type', models.CharField(choices=[('user', 'Extra user'), ('endpoint', 'Extra endpoint')], max_length=20)),
                ('monthly_toman', models.PositiveBigIntegerField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_rates', to='pricing.package')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('package', 'addon_type'), name='unique_package_addon')],
            },
        ),
        migrations.CreateModel(
            name='PackageFeatureTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('fa', 'فارسی'), ('en', 'English'), ('ar-ae', 'العربية')], max_length=10)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pricing.packagefeature')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('feature', 'locale'), name='unique_feature_locale')],
            },
        ),
        migrations.CreateModel(
            name='PackageFeatureValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=220)),
                ('is_included', models.BooleanField(default=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_values', to='pricing.packagefeature')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_values', to='pricing.package')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('package', 'feature'), name='unique_package_feature')],
            },
        ),
        migrations.CreateModel(
            name='PackageTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('fa', 'فارسی'), ('en', 'English'), ('ar-ae', 'العربية')], max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('audience', models.CharField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('sla_text', models.CharField(max_length=220)),
                ('cta_label', models.CharField(blank=True, max_length=100)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='pricing.package')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('package', 'locale'), name='unique_package_locale')],
            },
        ),
    ]
