# Generated by Django 5.2.17 on 2026-08-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='external_url',
            field=models.CharField(blank=True, help_text='Absolute URL or a locale-aware site path.', max_length=500),
        ),
    ]
