# Generated by Django 5.2.17 on 2026-08-22 06:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('primary', models.CharField(default='#2f6bff', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a six-digit hexadecimal color.')])),
                ('secondary', models.CharField(default='#0b1023', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a six-digit hexadecimal color.')])),
                ('accent', models.CharField(default='#31a9de', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a six-digit hexadecimal color.')])),
                ('background', models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a six-digit hexadecimal color.')])),
                ('surface', models.CharField(default='#f4f8ff', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a six-digit hexadecimal color.')])),
                ('foreground', models.CharField(default='#172039', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a six-digit hexadecimal color.')])),
                ('muted', models.CharField(default='#667085', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a six-digit hexadecimal color.')])),
                ('radius_small', models.PositiveSmallIntegerField(default=8)),
                ('radius_medium', models.PositiveSmallIntegerField(default=12)),
                ('radius_large', models.PositiveSmallIntegerField(default=20)),
                ('container_width', models.PositiveSmallIntegerField(default=1180)),
                ('section_spacing', models.PositiveSmallIntegerField(default=96)),
                ('motion_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'design settings',
            },
        ),
        migrations.CreateModel(
            name='RevalidationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.JSONField(default=list)),
                ('paths', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='core_revali_status_2de127_idx')],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton_key', models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ('brand_name', models.CharField(default='AbrIT', max_length=80)),
                ('phone', models.CharField(default='05131881000', max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('default_locale', models.CharField(choices=[('fa', 'فارسی'), ('en', 'English'), ('ar-ae', 'العربية')], default='fa', max_length=10)),
                ('customer_portal_url', models.URLField(blank=True)),
                ('external_checkout_url', models.URLField(blank=True)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('favicon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_favicons', to='media.mediaasset')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_logos', to='media.mediaasset')),
            ],
            options={
                'verbose_name_plural': 'site settings',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(default='admin', max_length=20)),
                ('action', models.CharField(max_length=80)),
                ('object_type', models.CharField(max_length=120)),
                ('object_id', models.CharField(max_length=64)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['object_type', 'object_id'], name='core_auditl_object__42e4a9_idx'), models.Index(fields=['-timestamp'], name='core_auditl_timesta_189a84_idx')],
            },
        ),
        migrations.CreateModel(
            name='SiteSettingsTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('fa', 'فارسی'), ('en', 'English'), ('ar-ae', 'العربية')], max_length=10)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('location_label', models.CharField(blank=True, max_length=120)),
                ('default_seo_title', models.CharField(blank=True, max_length=70)),
                ('default_seo_description', models.CharField(blank=True, max_length=170)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.sitesettings')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('settings', 'locale'), name='unique_site_locale')],
            },
        ),
    ]
