# Generated by Django 5.2.17 on 2026-08-22 06:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('kind', models.CharField(choices=[('page', 'Page'), ('service', 'Service'), ('solution', 'Solution'), ('knowledge', 'Knowledge'), ('news', 'News & Media')], max_length=20)),
                ('template_key', models.SlugField(default='default', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='content.contentitem')),
            ],
            options={
                'ordering': ('kind', 'key'),
            },
        ),
        migrations.CreateModel(
            name='ContentRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation_type', models.CharField(choices=[('related', 'Related'), ('service_solution', 'Service to solution'), ('service_knowledge', 'Service to knowledge'), ('news_service', 'News to service')], default='related', max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='content.contentitem')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='content.contentitem')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ContentTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('fa', 'فارسی'), ('en', 'English'), ('ar-ae', 'العربية')], max_length=10)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(allow_unicode=True, max_length=180)),
                ('path', models.CharField(help_text='Locale-relative public path without a leading slash.', max_length=500)),
                ('excerpt', models.TextField(blank=True)),
                ('workflow_status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('translation_status', models.CharField(choices=[('missing', 'Missing'), ('draft', 'Draft'), ('translated', 'Translated'), ('reviewed', 'Reviewed'), ('outdated', 'Outdated')], default='draft', max_length=16)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('source_revision', models.UUIDField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=70)),
                ('seo_description', models.CharField(blank=True, max_length=170)),
                ('canonical_url', models.URLField(blank=True)),
                ('robots_index', models.BooleanField(default=True)),
                ('robots_follow', models.BooleanField(default=True)),
                ('og_title', models.CharField(blank=True, max_length=100)),
                ('og_description', models.CharField(blank=True, max_length=220)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.contentitem')),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_graph_translations', to='media.mediaasset')),
            ],
            options={
                'ordering': ('item', 'locale'),
            },
        ),
        migrations.CreateModel(
            name='ContentRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('source', models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent'), ('mcp', 'MCP'), ('system', 'System')], default='admin', max_length=12)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='content.contenttranslation')),
            ],
            options={
                'ordering': ('-version',),
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_type', models.CharField(choices=[('hero', 'Hero'), ('rich_text', 'Rich Text'), ('feature_grid', 'Feature Grid'), ('service_grid', 'Service Grid'), ('stats', 'Stats'), ('steps', 'Steps'), ('faq', 'Faq'), ('cta', 'Cta'), ('pricing', 'Pricing'), ('network_visual', 'Network Visual')], max_length=40)),
                ('variant', models.CharField(choices=[('default', 'Default'), ('simple', 'Simple'), ('centered', 'Centered'), ('split', 'Split'), ('dashboard', 'Dashboard'), ('network', 'Network'), ('cards', 'Cards'), ('bento', 'Bento'), ('compact', 'Compact')], default='default', max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('schema_version', models.PositiveSmallIntegerField(default=1)),
                ('props', models.JSONField(default=dict)),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='content.contenttranslation')),
            ],
            options={
                'ordering': ('order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='TaxonomyTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=100)),
                ('kind', models.CharField(choices=[('knowledge_category', 'Knowledge category'), ('news_category', 'News category'), ('tag', 'Tag')], max_length=30)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'key'), name='unique_taxonomy_key')],
            },
        ),
        migrations.CreateModel(
            name='ArticleProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article_type', models.CharField(choices=[('knowledge', 'Knowledge'), ('news', 'News'), ('article', 'Article'), ('press_release', 'Press release'), ('announcement', 'Announcement'), ('event', 'Event'), ('video', 'Video'), ('gallery', 'Gallery')], max_length=30)),
                ('event_at', models.DateTimeField(blank=True, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article_profile', to='content.contentitem')),
                ('terms', models.ManyToManyField(blank=True, related_name='articles', to='content.taxonomyterm')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxonomyTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('fa', 'فارسی'), ('en', 'English'), ('ar-ae', 'العربية')], max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(allow_unicode=True, max_length=120)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.taxonomyterm')),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='technologies', to='media.mediaasset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capabilities', models.ManyToManyField(blank=True, related_name='services', to='content.capability')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_profile', to='content.contentitem')),
                ('technologies', models.ManyToManyField(blank=True, related_name='services', to='content.technology')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CapabilityTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('fa', 'فارسی'), ('en', 'English'), ('ar-ae', 'العربية')], max_length=10)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='content.capability')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('capability', 'locale'), name='unique_capability_locale')],
            },
        ),
        migrations.AddIndex(
            model_name='contentitem',
            index=models.Index(fields=['kind', 'is_active'], name='content_con_kind_071a22_idx'),
        ),
        migrations.AddConstraint(
            model_name='contentrelation',
            constraint=models.UniqueConstraint(fields=('source', 'target', 'relation_type'), name='unique_content_relation'),
        ),
        migrations.AddIndex(
            model_name='contenttranslation',
            index=models.Index(fields=['locale', 'workflow_status', 'published_at'], name='content_con_locale_5e28b9_idx'),
        ),
        migrations.AddIndex(
            model_name='contenttranslation',
            index=models.Index(fields=['locale', 'path'], name='content_con_locale_77a004_idx'),
        ),
        migrations.AddConstraint(
            model_name='contenttranslation',
            constraint=models.UniqueConstraint(fields=('item', 'locale'), name='unique_content_item_locale'),
        ),
        migrations.AddConstraint(
            model_name='contenttranslation',
            constraint=models.UniqueConstraint(fields=('locale', 'path'), name='unique_public_locale_path'),
        ),
        migrations.AddConstraint(
            model_name='contentrevision',
            constraint=models.UniqueConstraint(fields=('translation', 'version'), name='unique_revision_version'),
        ),
        migrations.AddConstraint(
            model_name='contentblock',
            constraint=models.UniqueConstraint(fields=('translation', 'order'), name='unique_block_order'),
        ),
        migrations.AddConstraint(
            model_name='taxonomytranslation',
            constraint=models.UniqueConstraint(fields=('term', 'locale'), name='unique_taxonomy_locale'),
        ),
    ]
