# Generated by Django 5.2.17 on 2026-08-22 06:44

import apps.forms.models
import apps.forms.validators
import django.core.files.storage
import django.db.models.deletion
import pathlib
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_privacy_consent', models.BooleanField(default=True)),
                ('retention_months', models.PositiveSmallIntegerField(default=12)),
                ('success_redirect', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('email', 'Email'), ('phone', 'Phone'), ('number', 'Number'), ('select', 'Select'), ('multi-select', 'Multi-select'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('date', 'Date'), ('datetime', 'Datetime'), ('url', 'URL'), ('file', 'File'), ('hidden', 'Hidden')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('min_length', models.PositiveIntegerField(blank=True, null=True)),
                ('max_length', models.PositiveIntegerField(blank=True, null=True)),
                ('regex', models.CharField(blank=True, max_length=500)),
                ('options', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms.form')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='FormFieldTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('fa', 'فارسی'), ('en', 'English'), ('ar-ae', 'العربية')], max_length=10)),
                ('label', models.CharField(max_length=180)),
                ('placeholder', models.CharField(blank=True, max_length=220)),
                ('help_text', models.TextField(blank=True)),
                ('option_labels', models.JSONField(blank=True, default=dict)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='forms.formfield')),
            ],
        ),
        migrations.CreateModel(
            name='FormSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('fa', 'فارسی'), ('en', 'English'), ('ar-ae', 'العربية')], max_length=10)),
                ('data', models.JSONField()),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_text', models.TextField(blank=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='forms.form')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FormTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('fa', 'فارسی'), ('en', 'English'), ('ar-ae', 'العربية')], max_length=10)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('success_message', models.TextField()),
                ('consent_label', models.TextField(blank=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='forms.form')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url=None, location=pathlib.PureWindowsPath('C:/projects/abrit.ir/backend/private-media/form-submissions')), upload_to=apps.forms.models.submission_file_path, validators=[apps.forms.validators.validate_submission_file])),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=120)),
                ('size', models.PositiveBigIntegerField()),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='forms.formsubmission')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.UniqueConstraint(fields=('form', 'key'), name='unique_form_field_key'),
        ),
        migrations.AddConstraint(
            model_name='formfield',
            constraint=models.UniqueConstraint(fields=('form', 'order'), name='unique_form_field_order'),
        ),
        migrations.AddConstraint(
            model_name='formfieldtranslation',
            constraint=models.UniqueConstraint(fields=('field', 'locale'), name='unique_form_field_locale'),
        ),
        migrations.AddConstraint(
            model_name='formtranslation',
            constraint=models.UniqueConstraint(fields=('form', 'locale'), name='unique_form_locale'),
        ),
    ]
