# Generated by Django 5.2.17 on 2026-08-22 06:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='library/%Y/%m/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('file', 'File')], max_length=20)),
                ('mime_type', models.CharField(max_length=120)),
                ('size', models.PositiveBigIntegerField()),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('checksum_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['media_type', 'is_public'], name='media_media_media_t_3543ae_idx')],
            },
        ),
        migrations.CreateModel(
            name='MediaAssetTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('fa', 'فارسی'), ('en', 'English'), ('ar-ae', 'العربية')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('alt', models.CharField(blank=True, max_length=300)),
                ('caption', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='media.mediaasset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('asset', 'locale'), name='unique_media_locale')],
            },
        ),
    ]
