# Generated by Django 5.2.17 on 2026-08-22 06:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('locale', models.CharField(choices=[('fa', 'فارسی'), ('en', 'English'), ('ar-ae', 'العربية')], max_length=10)),
                ('kind', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=180)),
                ('summary', models.TextField(blank=True)),
                ('normalized_text', models.TextField()),
                ('public_path', models.CharField(max_length=500)),
                ('translation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='search_document', to='content.contenttranslation')),
            ],
            options={
                'ordering': ('kind', 'title'),
                'indexes': [models.Index(fields=['locale', 'kind'], name='search_sear_locale_8d1ba8_idx'), models.Index(fields=['locale', 'title'], name='search_sear_locale_2866dc_idx')],
            },
        ),
    ]
